# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files D:/512/Minisys_new/prgmip32.coe
add_files D:/512/Minisys_new/dmem32.coe
add_files c:/Users/Fran/Desktop/test_31.coe
add_files c:/Users/Fran/Desktop/yanshou/prgmip32.coe
add_files c:/Users/Fran/Desktop/yanshou/dmem32.coe
add_files D:/512/Minisys_new/Minisys_new.runs/program_synth_1/program.dcp
set_property used_in_implementation false [get_files D:/512/Minisys_new/Minisys_new.runs/program_synth_1/program.dcp]
set_property use_blackbox_stub false [get_files D:/512/Minisys_new/Minisys_new.runs/program_synth_1/program.dcp]
add_files D:/512/Minisys_new/Minisys_new.runs/ram_synth_1/ram.dcp
set_property used_in_implementation false [get_files D:/512/Minisys_new/Minisys_new.runs/ram_synth_1/ram.dcp]
set_property use_blackbox_stub false [get_files D:/512/Minisys_new/Minisys_new.runs/ram_synth_1/ram.dcp]
read_verilog {
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/new/memori.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/new/ioread.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/Minisys_new/Ifect32.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/Minisys_new/Idecode32.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/Minisys_new/Execute32.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/Minisys_new/dmemory32.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/Minisys_new/control32.v
  D:/512/Minisys_new/Minisys_new.srcs/sources_1/imports/Minisys_new/minisys.v
  d:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/program/program_stub.v
  d:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram_stub.v
}
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/512/Minisys_new/Minisys_new.data/wt [current_project]
set_property parent.project_dir D:/512/Minisys_new [current_project]
synth_design -top minisys -part xc7a100tcsg324-1
write_checkpoint minisys.dcp
report_utilization -file minisys_utilization_synth.rpt -pb minisys_utilization_synth.pb
