# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip D:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram.xci
set_property used_in_implementation false [get_files d:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files D:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/512/Minisys_new/Minisys_new.data/wt [current_project]
set_property parent.project_dir D:/512/Minisys_new [current_project]
synth_design -top ram -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all ram
write_checkpoint -noxdef ram.dcp
report_utilization -file ram_utilization_synth.rpt -pb ram_utilization_synth.pb
if { [catch {
  file copy -force D:/512/Minisys_new/Minisys_new.runs/ram_synth_1/ram.dcp D:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram.dcp
  write_verilog -force -mode synth_stub D:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram_stub.v
  write_verilog -force -mode funcsim D:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram_funcsim.v
  write_vhdl -force -mode funcsim D:/512/Minisys_new/Minisys_new.srcs/sources_1/ip/ram/ram_funcsim.vhdl
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
